### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by billyjanitsch**
## Description

I was able to bump major versions of all outdated dependencies without breaking anything.

## Checklist

Please review this checklist before submitting a pull request.

- [x] Code compiles correctly
- [x] Created tests, if possible
- [x] All tests passing (`npm run test:all`)
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by agnivade** [comment]
@billyjanitsch - Can you test with `./bin/tldr -l` and `./bin/tldr -a` and confirm that it works ?

Also, I'm curious whether this fixes the uglify-js dependency error that github is giving after we upgraded to the caret dependencies.

**Comment by billyjanitsch** [comment]
@agnivade Yes, both of those commands work. The only non-dev dependency being updated is `ms`, for which the list of breaking changes is [small](https://github.com/zeit/ms/releases).

Where are you seeing the uglify-js dependency error? I can't reproduce it on master.

**Comment by agnivade** [comment]
> Where are you seeing the uglify-js dependency error?

Hmm .. maybe only the owner can see it.

Can you please rebase the latest master on to this and update the PR ? The ms is only used for a single call. I think I will remove it altogether sometime later.

**Comment by waldyrious** [comment]
>> Where are you seeing the uglify-js dependency error?

> Hmm .. maybe only the owner can see it.

screenshot from 2017-11-29 12-13-58

**Comment by billyjanitsch** [comment]
> Can you please rebase the latest master on to this and update the PR ?

Done! And, yes, this dependency upgrade happens to remove the (transitive) dependency of uglify-js entirely, so the security warning should go away.

**Pull request merged**
