### PR TITLE
Simplify package.json

### PR DESCRIPTION
**Pull request by zdroid**
- Use short repository property
- Use short bugs property
- Replace node >=0.10.0 with >=0.10

### CODE REVIEW

**Comment by waldyrious** [comment]
LGTM but I'm not versed in npm packages, so I'll let another maintainer merge this.

**Comment by zdroid** [comment]
@waldyrious Looks like nobody reacted for a week.

**Comment by waldyrious** [comment]
Cool. I'll merge using the new rebase feature, to test how it comes out :)

**Comment by waldyrious** [comment]
Meh, it still creates a [merge commit](https://github.com/tldr-pages/tldr-node-client/network), which IMO is unnecessary for a single-commit branch. It was good to get to know how it works, nevertheless.

**Comment by zdroid** [comment]
@waldyrious Have you tried squash merge? I haven't tried it yet. Maybe it gives the different result.

**Comment by waldyrious** [comment]
I did, it's what I use normally unless there are several atomic, well-worded commits that are worth preserving. It works pretty well :)

**Pull request merged**
