### PR TITLE
Github issue and pull request templates

### PR DESCRIPTION
**Pull request by igorshubovych**
- Create folder .github
- Move CONTRIBUTING.md to .github
- Create .github/ISSUE_TEMPLATE.md
- Create .github/PULL_REQUEST_TEMPLATE.md

### CODE REVIEW

**Comment by waldyrious** [comment]
:+1: this change overall, but I don't like the issue and PR templates as they stand. Rather than force a rigid structure on people, we could just have a sentence or two explaining what we expect and leave it to people's common sense to follow our recommendations as reasonable within the context of their contribution.

**Comment by igorshubovych** [comment]
@waldyrious can you come up with approximate text?

**Comment by waldyrious** [comment]
I was thinking something along the lines of "If you're reporting a bug, please include information on your environment, such as operating system name and version, and node version" (not all issues are bugs, some can be feature requests). For PRs, I don't have specific ideas since I am not familiar with node development, but the current template seems a little overbearing. But I'll leave it to your criterion to decide whether it could be made lighter/shorter without sacrificing clarity :)

**Comment by igorshubovych** [comment]
We can continue iterating over it. At the moment it already gives value.

**Pull request merged**
