### PR TITLE
Add the packaging metadata to build the tldr snap

### PR DESCRIPTION
**Pull request by elopio**
This is a package for the secure installation of apps that works in most Linux distributions.
Landing it upstream will enable builds for adventurous users.

### CODE REVIEW

**Comment by elopio** [comment]
You can find more information about snapcraft here: http://snapcraft.io/

Uploading the package to the snap ubuntu store is a great way to deliver the software to your users. 
In order to give it a try in ubuntu xenial, you can:

$ sudo apt install snapcraft git
$ git clone https://github.com/elopio/tldr-node-client
$ cd tldr-node-client
$ snapcraft
$ sudo snap install *.snap --dangerous
$ tldr --update
$ tldr curl

If you have any doubts or comments, please let me know :)

**Comment by agnivade** [comment]
Hi @elopio, thanks for the PR. It seems that snap is a new package management system for Linux distributions.

However, the tldr community also uses Macs and Windows. And I believe to add and maintain a new package management system just for Linux, along with npm creates an extra layer of complexity which is unwarranted, to be honest. Any metadata changes to packages have to be duplicated across both files.

I hope you agree with my reasoning here.

**Comment by elopio** [comment]
Hey @agnivade, thanks for reviewing. I understand that it will be extra work for you. I personally think that this will expose your project to many more linux users, so I consider it worth it. Of course, feel free to disagree and close the PR; I just found your project and tought it would be cool to use it in all my ubuntu devices.

Just one more note: the only extra metadata you need is this single yaml file. If you change something in your package.json, you don't have to change the yaml.

pura vida.

**Comment by agnivade** [comment]
> If you change something in your package.json, you don't have to change the yaml.

That's nice.

@waldyrious / @ostera - What do you think ?

**Comment by waldyrious** [comment]
I think that having a single extra file that allows this to be installed as a snap is a pretty good trade-off 👍

**Comment by agnivade** [comment]
Agree with the thinking. I assumed that this needed maintaining 2 files simultaneously. However, I am not very well-versed in snap(well duh, :sweat_smile: ). So any future modifications(barring very minor ones) to this file has to be done through @elopio. 

@elopio - Does this sound good to you ?

**Comment by elopio** [comment]
Of course, I'm here to help. You can ping me in an issue or a PR and I'll get the notification, or send me an email.

It would be better if you control the snap in the store, not me. Here are the steps: http://snapcraft.io/docs/build-snaps/publish

Please let me know if there's a piece of the snappy system that is not clear.

pura vida.

**Comment by agnivade** [comment]
Mmm .. so does this mean if I am publishing an update to npm, I will have to publish to snap store too ?

**Comment by elopio** [comment]
Yes.  But we can automate the publishing to the store. The exact workflow depends a lot on your preference though, the platforms you want to support and how complex is your pipeline. It could be as simple as telling travis to push every change to the stable channel of the store, or as complex as to involve builders for many architectures and various CI systems. Here are some nice options I've tried for some complex scenarios, to give you an idea of what's possible:

-  Push to the edge channel, amd64 platform every time there's a change in master, using travis ci and ubuntu xenial in docker. Push to the beta channel every time the edge snap passes the user acceptance tests I run in Jenkins. Push to the candidate channel every time a tag is added to the repo. Manually select the stable checkbox when I'm happy with the testing.
- Push to a branch in launchpad every time there's a change in master. Use launchpad to automatically build and push to the store for all architectures. I use different launchpad branches for the different channels.

In the end you just need a script somewhere that does snapcraft push $name.snap --channel

**Comment by waldyrious** [comment]
@elopio is you could guide us through the process of setting up such an automated workflow? I think pushing to edge on every commit, and to stable on every release would be enough, if that's possible. Step-by-step instructions would be greatly appreciated, as none of us have any experience with packaging snaps.

**Comment by agnivade** [comment]
> Yes. But we can automate the publishing to the store. 

That's great. A PR that publishes to the store using travis would be greatly appreciated ! Pushing to edge for every update, and pushing to stable for every version change in package.json should do the job !

**Comment by elopio** [comment]
Sure. I need to finish a few things and I'll get back to you with the steps.

**Comment by agnivade** [comment]
Perfect. Appreciate it. Once we have it, I am happy to merge the PR.

**Comment by elopio** [comment]
Hello again. I'm sorry for the delay. I was about to start a gist documenting it and remembered about 
https://lists.ubuntu.com/archives/snapcraft/2016-August/000831.html

We still need to document it officially, probably during our sprint next week. So I would appreciate a lot if you give it a try and let me know if there are things not crystal clear. I will experiment a little to find a simple way for travis to push to stable when a specific file changes.

pura vida.

**Comment by agnivade** [comment]
Thanks @elopio, this feels like a good starting point. I will merge this PR for now.

**Comment by elopio** [comment]
awesome, thank you.

**Comment by popey** [comment]
Hello! I noticed tldr was uploaded to the store by @agnivade back in November, but not released. There's a release button at the bottom of https://myapps.developer.ubuntu.com/dev/click-apps/6419/rev/1/ which @agnivade will need to press. In addition you might want to take a look at our updated documentation which details how to automate this so you don't have to worry about it. http://snapcraft.io/docs/build-snaps/ci-integration
Thanks!

**Pull request merged**
