### PR TITLE
Added autocompletion for zsh

### PR DESCRIPTION
**Pull request by rubenvereecken**
Wasn't too sure where to put this, open for discussion.
Also, this is the first time I wrote such an autocompletion page.

If we're cool with adding this, I'd like to have a little explanation at the bottom of the README or somewhere on the wiki since I don't think it's very straightforward to install.

### CODE REVIEW

**Comment by ostera** [comment]
Can you make it installable with the post-install npm hook? At the very least it should show me the command to append the right line to my `.zshrc`

**Comment by ostera** [comment]
Sorry, my last comment should've started like this: Fuck yes, thank you for this.

**Comment by rubenvereecken** [comment]
Sure thing, might make it happen tonight. The annoying bit is that I don't know how to install except by copying (or linking) it to a very particularly named file, then appending that file to some variable. This is the way to go about this, so best we can do is provide an explanation. That annoyed me.

**Comment by igorshubovych** [comment]
Wow! It is great!

Can you plz some short documentation/installation instruction?

**Comment by rubenvereecken** [comment]
Are we cool with having it at the bottom of the README?

```
# Autocompletion
- zsh: ...
```

Or even a link to the wiki.

The shortest installation instructions I can come up with:
- copy or link tldr.zsh to `my/completion/path/_tldr`
- add that path to `fpath` in your .zshrc: `fpath = (my/completion/path $fpath)`

Not scriptable since barely anyone has such a directory ready.

**Comment by rubenvereecken** [comment]
I opted for a README section. Proofreading welcome.

**Comment by waldyrious** [comment]
As a non-zsh user, the instructions look pretty clear :) I would only perhaps add a description of what the first two commands do (to match what was done with the second code block), but that's not critical.

**Comment by ostera** [comment]
If this script is included as part of the `npm` package, then it's trivial to provide the typical

```zsh
# Put this in your .zshrc file:
. /path/to/tldr-node/autocompletions/tldr.zsh
```

As part of the `post-install` hook.

**Comment by rubenvereecken** [comment]
Nope not sourcable

**Comment by rubenvereecken** [comment]
Yo guys I'd like to merge this :). I know it'd be nice if we could have it installed faster but this looks like a nice start.

**Pull request merged**
