### PR TITLE
fix issue #229 by removing dependency of render.spec.js on config.js

### LINKED ISSUE #229: npm run test fails for conflict with ~/.tldrrc
## Expected behaviour
`npm run test` should pass

## Actual behaviour
It doesn't pass for the current version of https://github.com/tldr-pages/tldr-node-client/commit/ef79714ef1cd50a45894059b26573fc3815afaac

Specifically the render.spec.js tests won't pass saying `TypeError: Cannot read property 'commandName' of undefined`. 

## Log, debug output

```
$ npm run test

> tldr@3.2.3 test /home/peng/github/tldr-node-client
> mocha test --require=env-test



  Cache
    ✓ should return a positive number on lastUpdate (1365ms)
    update()
      ✓ should use randomly created temp folder
      ✓ should remove temp folder after cache gets updated
    getPage()
      ✓ should return page contents for ls
      ✓ should return empty contents for svcs on OSX
      ✓ should return page contents for svcs on SunOS
      ✓ should return empty contents for non-existing page

  Config
    ✓ should load the default config
    ✓ should override the defaults with content from .tldrrc
    ✓ should validate the custom config format

  Index building
    failure
      ✓ shortIndex should not be created
    success
      ✓ correct shortIndex should be created

  Index
    ✓ should return correct list of all pages
    ✓ should return correct short index on getShortIndex()
    findPlatform()
      ✓ should find Linux platform for dd command
      ✓ should find platform common for cp command
      ✓ should not find platform for svcs command on Linux
      ✓ should not find platform for non-existing command
    commandsFor()
      ✓ should return correct list of pages for Linux
      ✓ should return correct list of pages for OSX
      ✓ should return correct list of pages for SunOS

  Parser
    ✓ parses the command name
    ✓ parses the description
    ✓ can parse the description on multiple lines
    ✓ does not escape HTML entities
    ✓ parses example descriptions and codes
    ✓ does not escape HTML in the examples either
    ✓ parses all the examples
    ✓ leaves out malformed examples
    ✓ should parse description with inline code
    ✓ should parse examples with inline code
    ✓ should parse code examples with unix redirects ">", "<", ">>" and "<<<"
    See also section
      ✓ should parse seeAlso commands when mentioned in description
      ✓ should parse seeAlso commands when mentioned in examples
      ✓ should have only unique seeAlso commands when mentioned a few times

  Platform
    getPreferredPlatform
      ✓ should return the running platform with no configuration
      ✓ should overwrite the running platform if configured
      ✓ should return current system platform if configuration is wrong
    isSupported
      ✓ should tell that Linux, OSX, SunOS and Win32 are supported
    resolve
      ✓ should resolve tar command with specific OS and common folder

  Render
    1) surrounds the output with blank lines
    2) contains the command name
    3) contains the description name
    4) highlights replaceable {{tokens}}
    5) should correctly render see also section

  Search
    ✓ should create index
    ✓ should perform searches

  Theme
    Rendering
      ✓ should render name with green and bold
      ✓ should render description with red and underline
      ✓ should render example description with blue
      ✓ should render example code with blue
      ✓ should render example argument with yellow, dim, underline
    Rendering with new theme colors
      ✓ should render name with greenBright and bold
      ✓ should render description with greenBright and bold
      ✓ should render example description with greenBright
      ✓ should render example code with redBright
      ✓ should render example argument with white


  52 passing (1s)
  5 failing

  1) Render
       surrounds the output with blank lines:
     TypeError: Cannot read property 'commandName' of undefined
      at Theme.getStylingFunction (lib/theme.js:25:28)
      at Theme.renderCommandName (lib/theme.js:30:17)
      at Object.exports.toANSI (lib/render.js:28:28)
      at Context.it (test/render.spec.js:14:23)

  2) Render
       contains the command name:
     TypeError: Cannot read property 'commandName' of undefined
      at Theme.getStylingFunction (lib/theme.js:25:28)
      at Theme.renderCommandName (lib/theme.js:30:17)
      at Object.exports.toANSI (lib/render.js:28:28)
      at Context.it (test/render.spec.js:24:23)

  3) Render
       contains the description name:
     TypeError: Cannot read property 'commandName' of undefined
      at Theme.getStylingFunction (lib/theme.js:25:28)
      at Theme.renderCommandName (lib/theme.js:30:17)
      at Object.exports.toANSI (lib/render.js:28:28)
      at Context.it (test/render.spec.js:34:23)

  4) Render
       highlights replaceable {{tokens}}:
     TypeError: Cannot read property 'commandName' of undefined
      at Theme.getStylingFunction (lib/theme.js:25:28)
      at Theme.renderCommandName (lib/theme.js:30:17)
      at Object.exports.toANSI (lib/render.js:28:28)
      at Context.it (test/render.spec.js:44:23)

  5) Render
       should correctly render see also section:
     TypeError: Cannot read property 'commandName' of undefined
      at Theme.getStylingFunction (lib/theme.js:25:28)
      at Theme.renderCommandName (lib/theme.js:30:17)
      at Object.exports.toANSI (lib/render.js:28:28)
      at Context.it (test/render.spec.js:58:23)



npm ERR! code ELIFECYCLE
npm ERR! errno 5
npm ERR! tldr@3.2.3 test: `mocha test --require=env-test`
npm ERR! Exit status 5
npm ERR! 
npm ERR! Failed at the tldr@3.2.3 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/peng/.npm/_logs/2018-07-23T21_08_54_098Z-debug.log

```

## Environment
- Operating system: Ubuntu 16.04.3 LTS
- NodeJS version: v10.6.0

### PR DESCRIPTION
**Pull request by gpenghe**
## Description
This PR fixes #229.

To test it, put the following content in your `$HOME/.tldrrc` before applying the change:

```
{
  "themes": {
    "ocean": {
      "commandName": "bold, cyan",
      "mainDescription": "",
      "exampleDescription": "green",
      "exampleCode": "cyan",
      "exampleToken": "dim"
    }
  },
  "theme": "ocean"
}

```
The `npm test` should fail as described in #229. Then apply this change, it should pass.

## Checklist

Please review this checklist before submitting a pull request.

- [X] Code compiles correctly
- [X] Created tests, if possible
- [X] All tests passing (`npm run test:all`)
- [X] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by gpenghe** [comment]
Hope this (bc82031) fixed the previous problem. Proved again 12am coding is not a good thing...

BTW, the reason why the the previous incorrect patch works: the end effect of that patch is mainly removing the line of `config.get().theme = 'base16';`, which disables the resetting of the `theme` in the test and thus accidently fixes the problem of `base16` theme not found in the loaded external configurations. I've tried that removing `config.get().theme = 'base16';` alone will fix the issue #229. But still, using stub to remove the dependency on `config.js` should be the right approach.

**Comment by gpenghe** [comment]
BTW, when merging, please squash 395a4ae and bc82031 together -- better not make the first one appear in history...

**Comment by gpenghe** [comment]
@agnivade This PR is a bit messed up. I did a merge after the two commits which might makes it a bit confusing but I thought it was still mergeable. But then you pushed another commit, https://github.com/gpenghe/tldr-node-client/commit/e9b50333d63f27fa169492d9b0f4062eb0433940, somehow into my fork... I didn't expect that could happen. I mean origin repo can push to forked repo directly?

**Comment by gpenghe** [comment]
Re-submitted this patch as #235. Closing this one.

**Comment by agnivade** [comment]
Yes, your branch was out of date when I updated master with your other PR. So I synced master back into this one. While merging the PR, I would have squashed all commits anyways. But it seems you deleted the branch already. Not an issue.

**Pull request closed without merging**
