### PR TITLE
Fix #12, #19: download pages zip archive from tldr-pages.github.io static site instead of Github API

### LINKED ISSUE #12: Update fails (invalid signature)
Just copying the issue from tldr-pages/tldr#263. 

Related error:
```
➜  ~  tldr --update
Updating...
Error: invalid signature: 0x2e736370
    at /usr/local/lib/node_modules/tldr/node_modules/unzip/lib/parse.js:59:13
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

A lot of people are getting them it seems, including a friend I introduced to the client. It may also be the cause of #11 because the cache got filled improperly.

### PR DESCRIPTION
**Pull request by igorshubovych**
[tldr-pages.github.io] has static assets automatically built by Travis CI:

- Fresh build of [pages archive](http://tldr-pages.github.io/assets/tldr.zip) together index.json
- Plain fresh [index.json](http://tldr-pages.github.io/assets/index.json)

Note: currently it is built from my own fork: https://github.com/igorshubovych/tldr. But soon I will merge it to the main repo.

Github API which is currently used by `tldr-node-client`, is often slow, probably because it regenerates file on the fly. I changed it to download from static site.

I tested it several times with and without my fixes and here are the results:

- Downloading from static site - always finishes successfully, took around 0.8 - 0.9 sec
- Downloading from Github API - seems like depends on availability of Github API (not sure if Github caches it), it sometimes updates successfully, took around 1 sec, and sometimes does not work at all for hours

It seems like this PR will fix #12, #19 and [#319](https://github.com/tldr-pages/tldr/issues/319) bug from tldr repo.

Log of updating with PR applied:
~~~
$ NODE_ENV=development node ./bin/tldr --clear-cache
Done

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Done
NODE_ENV=development node ./bin/tldr --update  0.87s user 0.16s system 47% cpu 2.163 total

$ NODE_ENV=development node ./bin/tldr --clear-cache
Done

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Done
NODE_ENV=development node ./bin/tldr --update  0.86s user 0.15s system 107% cpu 0.938 total

$ NODE_ENV=development node ./bin/tldr --clear-cache
Done

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Done
NODE_ENV=development node ./bin/tldr --update  0.89s user 0.18s system 111% cpu 0.968 total
~~~

Log of updating without PR applied:

~~~
$ NODE_ENV=development node ./bin/tldr --clear-cache
Done

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:363:17)
NODE_ENV=development node ./bin/tldr --update  0.88s user 0.15s system 50% cpu 2.046 total

$ NODE_ENV=development node ./bin/tldr --clear-cache
Done

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Error: invalid bit length repeat
    at Zlib._handle.onerror (zlib.js:363:17)
NODE_ENV=development node ./bin/tldr --update  0.88s user 0.15s system 53% cpu 1.912 total

$ NODE_ENV=development node ./bin/tldr --clear-cache
Done

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Error: invalid signature: 0xb68c7950
    at /Users/igor/Projects/tldr-node-client/node_modules/unzip2/lib/parse.js:63:13
    at processImmediate [as _immediateCallback] (timers.js:383:17)
NODE_ENV=development node ./bin/tldr --update  0.89s user 0.18s system 54% cpu 1.968 total

$ NODE_ENV=development node ./bin/tldr --clear-cache
Done

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Done
^C
NODE_ENV=development node ./bin/tldr --update  37.46s user 3.68s system 96% cpu 42.554 total

$ NODE_ENV=development node ./bin/tldr --clear-cache
Done

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Error: invalid signature: 0xb68c4b50
    at /Users/igor/Projects/tldr-node-client/node_modules/unzip2/lib/parse.js:63:13
    at processImmediate [as _immediateCallback] (timers.js:383:17)
NODE_ENV=development node ./bin/tldr --update  0.90s user 0.17s system 53% cpu 1.997 total

$ NODE_ENV=development node ./bin/tldr --clear-cache
Done

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Error: invalid signature: 0xb68c4b50
    at /Users/igor/Projects/tldr-node-client/node_modules/unzip2/lib/parse.js:63:13
    at processImmediate [as _immediateCallback] (timers.js:383:17)
NODE_ENV=development node ./bin/tldr --update  0.89s user 0.16s system 55% cpu 1.891 total

$ NODE_ENV=development node ./bin/tldr --clear-cache
Done

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Error: invalid signature: 0xb68c4b50
    at /Users/igor/Projects/tldr-node-client/node_modules/unzip2/lib/parse.js:63:13
    at processImmediate [as _immediateCallback] (timers.js:383:17)
NODE_ENV=development node ./bin/tldr --update  0.86s user 0.16s system 54% cpu 1.865 total

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Error: invalid signature: 0xb68c7950
    at /Users/igor/Projects/tldr-node-client/node_modules/unzip2/lib/parse.js:63:13
    at processImmediate [as _immediateCallback] (timers.js:383:17)
NODE_ENV=development node ./bin/tldr --update  0.87s user 0.16s system 54% cpu 1.881 total

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Error: invalid signature: 0xb68c7950
    at /Users/igor/Projects/tldr-node-client/node_modules/unzip2/lib/parse.js:63:13
    at processImmediate [as _immediateCallback] (timers.js:383:17)
NODE_ENV=development node ./bin/tldr --update  0.93s user 0.18s system 55% cpu 1.988 total

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:363:17)
NODE_ENV=development node ./bin/tldr --update  0.91s user 0.17s system 55% cpu 1.942 total

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Error: invalid signature: 0xf0d4ab47
    at /Users/igor/Projects/tldr-node-client/node_modules/unzip2/lib/parse.js:63:13
    at processImmediate [as _immediateCallback] (timers.js:383:17)
NODE_ENV=development node ./bin/tldr --update  0.89s user 0.16s system 55% cpu 1.888 total

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Error: invalid signature: 0xf0d4ab47
    at /Users/igor/Projects/tldr-node-client/node_modules/unzip2/lib/parse.js:63:13
    at processImmediate [as _immediateCallback] (timers.js:383:17)
NODE_ENV=development node ./bin/tldr --update  0.86s user 0.16s system 54% cpu 1.882 total

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Error: invalid signature: 0xb68c7950
    at /Users/igor/Projects/tldr-node-client/node_modules/unzip2/lib/parse.js:63:13
    at processImmediate [as _immediateCallback] (timers.js:383:17)
NODE_ENV=development node ./bin/tldr --update  0.87s user 0.16s system 52% cpu 1.975 total

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:363:17)
NODE_ENV=development node ./bin/tldr --update  0.86s user 0.16s system 45% cpu 2.251 total

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Error: invalid signature: 0x61702f72
    at /Users/igor/Projects/tldr-node-client/node_modules/unzip2/lib/parse.js:63:13
    at processImmediate [as _immediateCallback] (timers.js:383:17)
NODE_ENV=development node ./bin/tldr --update  0.91s user 0.17s system 55% cpu 1.925 total

$ time NODE_ENV=development node ./bin/tldr --update
Updating...
Done
^C
NODE_ENV=development node ./bin/tldr --update  88.99s user 8.66s system 97% cpu 1:40.66 total
~~~

### CODE REVIEW

**Comment by rprieto** [comment]
Very nice work!! It's great you managed to get to the bottom of all these `invalid signature` errors. Should we wait until the static assets are built off master before merging?

**Comment by igorshubovych** [comment]
They are built already!

Check them out
- https://github.com/tldr-pages/tldr-pages.github.io/commits/master
- http://tldr-pages.github.io/assets/tldr.zip
- http://tldr-pages.github.io/assets/index.json

**Comment by igorshubovych** [comment]
Please don't merge yet. It suspiciously fails on `tldr tar`

**Comment by igorshubovych** [comment]
I have just fixed really weird issue which happened while unzipping pages archive.

Before 5807688, it downloaded pages archive, but unzip only half of it. I previously tested it with `tldr git`, and unfortunately it worked, but `tldr tar` did not work.

I had to use `close` event of Stream instead of `finish`. It is probably related to this:
https://nodejs.org/api/stream.html#stream_event_close

But I will lie, if I say I understand it. If anybody can explain why it started to work, I would listen with pleasure.

**Comment by igorshubovych** [comment]
Well. At least they are using `close` event everywhere in tests:
https://github.com/glebdmitriew/node-unzip-2/tree/master/test

I wonder how it worked before.

**Comment by igorshubovych** [comment]
http://stackoverflow.com/questions/33907647/how-to-get-entry-list-of-zip-file-using-unzip2-of-nodejs

**Comment by igorshubovych** [comment]
It seems like I fixed it.

So now it is possible to mention in ~/.tldrrc

~~~json
{
  "repository" : "igorshubovych/tldr#master"
}
~~~

By default it loads from http://tldr-pages.github.io/assets/tldr.zip

**Pull request merged**
