### PR TITLE
Fixing failing tests

### PR DESCRIPTION
**Pull request by agnivade**
## Description
Fixed unit tests that were failing
Tied down dev dependencies to minor releases. Keeping it up-to-date is a bad idea and will break code like it did here. We can always intentionally upgrade any package we want.

## Checklist

Please review this checklist before submitting a pull request.

- [x] Code compiles correctly
~~- [ ] Created tests, if possible~~
- [x] All tests passing (`npm run test:all`)
~~- [ ] Extended the README / documentation, if necessary~~

### CODE REVIEW

**Comment by agnivade** [comment]
@waldyrious - Quick review ? You can merge #150 after we push this.

**Comment by waldyrious** [comment]
I'm have pretty much zero node.js development experience, but the changes do look reasonable to me, and tests are indeed fixed. I'll squash-merge to edit the final commit message a bit, hope you don't mind.

**Comment by waldyrious** [comment]
Could we set up greenkeeper to automatically submit PRs to update dependencies when new versions are released?

**Comment by agnivade** [comment]
Ugh .. this is one thing I hate about Node. There's always this cat and mouse game you have to play to keep your dependencies up to date. I'd rather update dependencies when I feel like it. That's why I removed the david-dm dependency checker.

**Comment by waldyrious** [comment]
Yeah but automated PRs are simpler to handle, right?

If tests don't break for those PRs, we can simply merge them and get, say, security updates or bug fixes for edge cases we hadn't been exposed to yet.

If the tests do break, that gives us a heads up and we can start considering how to adjust them (as you did here), rather than being caught by surprise later on.

**Comment by agnivade** [comment]
I understand all that. My point wasn't about simplicity. It's a mental barrier I have that I don't like overdoing software. It doesn't matter that an automated tool is doing it or I am doing it manually, the fact that its been done is what bothers me.

I don't really see any need to always remain up-to-date here. We anyway use a small no. of dependencies. I would prefer if its kept that way.

**Comment by waldyrious** [comment]
Fair enough, I can understand that POV.

**Pull request merged**
