### PR TITLE
config.js: add more theme colors

### PR DESCRIPTION
**Pull request by jsonbruce**
Refer to the [chalk documentation](https://github.com/chalk/chalk#styles)

## Description
Please explain the changes you made here.

## Checklist

Please review this checklist before submitting a pull request.

- [x] Code compiles correctly
- [ ] Created tests, if possible
- [ ] All tests passing (`npm run test:all`)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by agnivade** [comment]
Looks good. Can you add a test for this ?

**Comment by jsonbruce** [comment]
Add test case to the `test/theme.spec.js`, right?

**Comment by agnivade** [comment]
Yes, I think theme.spec.js as well as one in config.spec.js should do.

**Comment by jsonbruce** [comment]
I have added test case for new theme colors.
All tests are green on my local machine.

**Comment by agnivade** [comment]
Should this PR be closed then ? Since the new PR contains all the changes.

**Comment by waldyrious** [comment]
For future reference, the new PR is #196.

**Pull request closed without merging**
