### PR TITLE
Windows support

### LINKED ISSUE #10: support for windows
- it would be nice if it runs on windows

### PR DESCRIPTION
**Pull request by Mopolo**
Fix #10 

I added support for Windows by using a cross-platform way of grabing the user homedir with [os-homedir](https://www.npmjs.com/package/os-homedir) (`os.homedir()` only works since node 4).

I ran tests in the default Windows terminal and in gitbash and both passed.

### CODE REVIEW

**Comment by igorshubovych** [comment]
Wow. Thanks! Great work!

Could you please run the following commands in PowerShell?

~~~shell
node ./bin/tldr zip && sleep 2 && \
node ./bin/tldr --update && \
node ./bin/tldr git && sleep 2 && \
node ./bin/tldr --clear-cache && \
node ./bin/tldr --update && \
node ./bin/tldr tar && \
node ./bin/tldr git && \
node ./bin/tldr --render test.md
~~~

**Comment by Mopolo** [comment]
It works in PowerShell bu I had to adapt your script to the PowerShell syntax:

```powershell
node ./bin/tldr zip ; sleep 2 ; `
node ./bin/tldr --update ; `
node ./bin/tldr git ; sleep 2 ; `
node ./bin/tldr --clear-cache ; `
node ./bin/tldr --update ; `
node ./bin/tldr tar ; `
node ./bin/tldr git ; `
node ./bin/tldr --render test.md
```

Yours works fine in gitbash.

**Comment by igorshubovych** [comment]
Great! Then I will merge it soon and release a new version.

**Comment by Mopolo** [comment]
Nice thanks :smile:

**Pull request merged**
