### PR TITLE
perf: ⚡️ replace request with axios

### PR DESCRIPTION
**Pull request by rodrigograca31**
## Description
As I described in #234 `request` is slow and deprecated. This change
replaces it with `axios` which is a better alternative. This also
removes the proxy configuration because it wasn't even working (no
`.get()` when setting the defaults) and `axios` supports `http_proxy` by
default (I tested)

## Checklist

Please review this checklist before submitting a pull request.

- [x] Code compiles correctly
- [x] Created tests, if possible
- [x] All tests passing (`npm run test:all`)
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by rodrigograca31** [comment]
The failing tests are a fluke.

[On my fork they all pass as you can see here](https://github.com/rodrigograca31/tldr-node-client/actions/runs/304146644). @tldr-pages Please re-run then.

**Comment by agnivade** [comment]
Thank you for your time @rodrigograca31 ! Let's bring the discussion at https://github.com/tldr-pages/tldr-node-client/issues/234 to a conclusion before continuing with this PR.

**Review by agnivade — APPROVED** [review]
Looks good to me @rodrigograca31 !

It'll be great if you can capture some of the performance results from the issue in this PR for posterity.

I'll give it a few days for @vladimyr to give it a look.

**Comment by rodrigograca31** [comment]
As requested:

Here are the performance results with the mean and median values that clearly show a reduction of about 50% in loading time of `axios` vs `got`: (includes the tests by/in two different users/machines)
image


[Data file: axios_got.xlsx](https://github.com/tldr-pages/tldr-node-client/files/5390390/axios_got.xlsx)

**Comment by rodrigograca31** [comment]
Just solved the conflicts that were caused by the merging of PR #313

**Comment by rodrigograca31** [comment]
Yay! awesome! :heart:

**Pull request merged**
