### PR TITLE
Add command line option "--windows"

### PR DESCRIPTION
**Pull request by marchersimon**
## Description
I added the command line option "--windows", since the functionality already was there, just the option was missing.

## Checklist

- [x] Code compiles correctly
- [ ] Created tests, if possible
- [ ] All tests passing (`npm run test:all`)
- [x] Extended the README / documentation, if necessary

I didn't modify any tests, since I don't know what I should change. Also I'm sorry if I made any mistakes, I hardly know any javascript.

### CODE REVIEW

**Review by bl-ue — APPROVED** [review]
Looks great, of course.  I wonder why it wasn't there before, but I guess @agnivade will tell us.

**Review by agnivade — CHANGES_REQUESTED** [review]
Can we add a test please?

**Comment by bl-ue** [comment]
Yes, sure.  Where should I add it? [`test/parser.spec.js`](https://github.com/tldr-pages/tldr-node-client/blob/master/test/parser.spec.js)?

**Comment by marchersimon** [comment]
I'm not entirely sure what you mean by test, but I just added it to `functional-test.sh`

**Review by agnivade — APPROVED** [review]
Thank you @marchersimon

**Pull request merged**
