### PR TITLE
Help message formatting

### PR DESCRIPTION
**Pull request by vladimyr**
## Description
Re-formatting help output :art: 
Changes are shown bellow...

### Old formatting
old

### New formatting :tada:
new

## Checklist

Please review this checklist before submitting a pull request.

- [x] Code compiles correctly
- [ ] Created tests, if possible
- [ ] All tests passing (`npm run test:all`)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by agnivade** [comment]
Thanks. Let me know if you would be interested to become a collaborator of the repo.

**Comment by vladimyr** [comment]
> Thanks. Let me know if you would be interested to become a collaborator of the repo.

Thanks for your kind offer but lets leave it open for now.
I'm not sure in my longtime availability and appropriate response time due to my daily job requirements. That being said you can count on me jumping in during my free time either fixing some new issue or tweaking existing stuff. :wink:

**Comment by agnivade** [comment]
That's not an issue. Being a collaborator does not require you to be available all the time. It is just a mark that you have contributed significantly to the project and can help in making reviews whenever you have time. Let me know if this sounds good to you.

**Comment by vladimyr** [comment]
> contributed significantly

That's some strong wording having in mind what I actually did here :grin: 
I cheerfully accept my new title: _flying_ collaborator :+1:

**Comment by agnivade** [comment]
Done !

**Pull request merged**
