### PR TITLE
package.json: Add funding information

### PR DESCRIPTION
**Pull request by kbdharun**
Signed-off-by: K.B.Dharun Krishna <kbdharunkrishna@gmail.com>

## Description

Adding Liberapay to funding information in `package.json` to show up during `npm install` and `npm fund` commands. Ref: https://github.com/npm/rfcs/blob/main/implemented/0017-add-funding-support.md

image

## Checklist

Please review this checklist before submitting a pull request.

- [ ] Code compiles correctly
- [ ] Created tests, if possible
- [x] All tests passing (`npm run test:all`)

```powershell
 npm run test:all

> tldr@3.3.8 test:all
> npm run lint && npm test && npm run test:functional


> tldr@3.3.8 lint
> eslint lib test bin/tldr

'eslint' is not recognized as an internal or external command,
operable program or batch file.
```

- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Review by owenvoke — APPROVED** [review]
Probably worth getting some other approvals to be sure, but makes sense to me. 👍🏻

**Review by sbrl — APPROVED** [review]
Looks ok to me, good thinking.

> 'eslint' is not recognized as an internal or external command,
operable program or batch file.

I believe you need to run `npm install` or do `npm install -g eslint` I think? Not sure. BUt that doesn't matter all that much for this PR I don't think.

**Comment by kbdharun** [comment]
> Looks ok to me, good thinking.
> 
> > 'eslint' is not recognized as an internal or external command,
> > operable program or batch file.
> 
> I believe you need to run `npm install` or do `npm install -g eslint` I think? Not sure. BUt that doesn't matter all that much for this PR I don't think.

That isn't related I think because ` npm run test:all` would have probably run the tests for all packages in system (I only have 2 installed `tldr`, `tldr-lint`.

**Review by waldyrious — APPROVED** [review]
Makes sense!

**Pull request merged**
