### PR TITLE
Allow searching for multi-word commands

### PR DESCRIPTION
**Pull request by mcm69**
e.g. `tldr git commit`

### CODE REVIEW

**Comment by berkus** [comment]
Linked https://github.com/tldr-pages/tldr-cpp-client/pull/5

**Comment by waldyrious** [comment]
+:100: this would be very convenient indeed!

**Comment by Leandros** [comment]
All integrated. Update published via homebrew.

**Comment by rprieto** [comment]
I like the idea. It's a tricky one though, given that some complex commands have a page per sub-command (git-log, git-push) but some have a single page with everything (docker). Maybe joining is better than not doing anything though :)

**Comment by amitzur** [comment]
:-1: man doesn't support it, and I think the commit is specific to git. Isn't it the case that not all multi word commands should be joined with a dash?

**Comment by mcm69** [comment]
@amitzur well, this is not `man` anyway. Also, as we do have pages for `git commit` and many more multi-word commands (which are saved in the format of `git-commit.md`), it did not make much sense searching for them as `tldr git-commit`. There's no such command as `git-commit` after all.

**Comment by igorshubovych** [comment]
Thank you for contribution. It gave me an idea on to do it.
There is more sophisticated checks done in #80.

**Pull request closed without merging**
