### PR TITLE
Add node 16 and 18 to test matrix

### PR DESCRIPTION
**Pull request by MasterOdin**
## Description

PR adds node 16 and 18 to our test matrix to ensure the client works against the latest LTS releases. Unlike #352, I chose not to bump the minimum engine version as the codebase given that not yet using anything that wouldn't work against node 10.

## Checklist

Please review this checklist before submitting a pull request.

- [x] Code compiles correctly
- [x] Created tests, if possible
- [x] All tests passing (`npm run test:all`)
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by agnivade** [comment]
Node 10,12,13 have gone out of support quite a while back. IMO it's a bit wasteful to use CI resources on those versions. I think we should do a major version release and drop support for those old versions.

**Comment by owenvoke** [comment]
@agnivade, that definitely makes sense too 👍🏻

**Comment by MasterOdin** [comment]
I would prefer to do that in a follow-up PR as I view the two topics of "test against newer versions of node" and "raise the lowest supported node version" as separate.

**Comment by agnivade** [comment]
> I would prefer to do that in a follow-up PR as I view the two topics of "test against newer versions of node" and "raise the lowest supported node version" as separate.

Both are related, but not a big deal. We can merge this.

**Pull request merged**
